name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Déploiement sur le VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd CodeArena-Frontend/
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"

            npm install
            npm run build

            if command -v docker-compose >/dev/null 2>&1; then
              docker-compose down
              docker-compose up --build -d
            else
              docker compose down
              docker compose up --build -d
            fi
